slogan: "Information wants to be free."

show_heart: true
show_slogan: true

menu:
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

  - title: "LinkedIn"
    url: https://www.linkedin.com/in/jessy-sobreiro
    intro: "My LinkedIn account"
    icon: "fa fa-linkedin"

  - title: "GitHub"
    url: https://www.github.com/jess-sys
    intro: "My GitHub"
    icon: "fa fa-github"

links:

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: false
favicon: favicon.png
#duoshuo_shortname: 


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-70812759-1


# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
#valine comment (change to yours)
valine: 
  enable: true
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: "TEST"
  visitor: true
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
